// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arzxemyvtnucygdsmonb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyenhlbXl2dG51Y3lnZHNtb25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0NDA3NDUsImV4cCI6MjA4MDAxNjc0NX0.h-S9NCcmzJPTXBmU-amHf0st4nACqIZq02kKnhOMcug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});